/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary-fixed": "#d8e2ff",
                "on-surface-variant": "#424754",
                "on-tertiary": "#ffffff",
                "on-primary-fixed-variant": "#004397",
                "surface-container": "#ecedf8",
                "on-primary-container": "#edf0ff",
                "outline-variant": "#c2c6d6",
                "inverse-primary": "#aec6ff",
                "surface-container-lowest": "#ffffff",
                "primary-container": "#0668e1",
                "on-tertiary-fixed": "#360f00",
                "secondary-fixed-dim": "#afc6fd",
                "inverse-surface": "#2e3038",
                "on-surface": "#191b23",
                "secondary": "#475e8e",
                "error-container": "#ffdad6",
                "surface-tint": "#0059c5",
                "surface-bright": "#faf9ff",
                "secondary-fixed": "#d8e2ff",
                "on-tertiary-container": "#ffede6",
                "on-primary": "#ffffff",
                "primary-fixed-dim": "#aec6ff",
                "primary": "#0051b3",
                "on-secondary": "#ffffff",
                "surface-dim": "#d8d9e4",
                "surface": "#faf9ff",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#001a43",
                "tertiary-fixed": "#ffdbcd",
                "outline": "#727785",
                "tertiary-fixed-dim": "#ffb596",
                "on-secondary-container": "#3b5281",
                "tertiary-container": "#bc4800",
                "on-secondary-fixed-variant": "#2f4675",
                "surface-container-highest": "#e1e2ec",
                "secondary-container": "#afc6fd",
                "tertiary": "#943700",
                "on-background": "#191b23",
                "inverse-on-surface": "#eff0fb",
                "surface-variant": "#e1e2ec",
                "on-tertiary-fixed-variant": "#7d2d00",
                "background": "#faf9ff",
                "surface-container-high": "#e6e7f2",
                "surface-container-low": "#f2f3fe",
                "error": "#ba1a1a",
                "on-primary-fixed": "#001a43",
                "on-error": "#ffffff",
                "success": "#0f5223",
                "success-container": "#d8f5e1"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            boxShadow: {
                'editorial': '0 24px 48px -12px rgba(25, 27, 35, 0.08)',
            }
        },
    },
    plugins: [],
}
